# Generated by Django 3.2.8 on 2022-08-17 09:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_auto_20220817_1223'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='todo',
            options={'ordering': ['-id']},
        ),
    ]
