# Generated by Django 3.2.8 on 2022-08-17 09:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='todouser',
            options={'ordering': ['-id']},
        ),
    ]
